source 'https://github.com/CocoaPods/Specs.git'

target "NBNRealmBrowser", :exclusive => true do
  pod "NBNRealmBrowser", :path => "../"
end

target "Tests", :exclusive => true do
  pod 'KIF', '~> 3.3.0'
end
